cp ../scoreQuarantine2/bach_bwv1007-06.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_bwv1010-07.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_partita1-2.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_partita1-3.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_partita1-4.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_partita1-6.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_partita1-8.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_partita2-4.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_partita3-6.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_partita3-7.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_sonata1-4.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_sonata2-4.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/bach_sonata3-4.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/clementi_sonatina-36-3-3.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh01.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh03.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh05.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh06.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh07.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh08.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh09.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh10.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh11.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh12.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh14.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh15.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh17.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh19.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh20.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh21.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh24.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh25.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh26.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/gershwin_gersh27.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/mozart_k439b.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/schubert_hydraulicus.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/schumann_op35-no03.score.xml ../scoreQuarantine3/
cp ../scoreQuarantine2/schumann_tmte04-63m.score.xml ../scoreQuarantine3/
